sudo: required

language: cpp

services:
  - docker

matrix:
  include:
     # Linux
     - os: linux
       env:
         - NODE_VERSION="4.0.0"
         - CB_VERSION="enterprise-4.0.0-rc0"
     - os: linux
       env:
         - NODE_VERSION="3.3.0" # node abi 45
         - CB_VERSION="enterprise-4.0.0-rc0"
     - os: linux
       env:
         - NODE_VERSION="0.12.7" # node abi 14
         - CB_VERSION="enterprise-3.0.3"
     - os: linux
       env:
         - NODE_VERSION="0.12.7" # node abi 14
         - CB_VERSION="enterprise-4.0.0-rc0"
     - os: linux
       env:
         - NODE_VERSION="0.10.40" # node abi 11
         - CB_VERSION="enterprise-4.0.0-rc0"
     # OS X
     - os: osx
       env:
         - NODE_VERSION="4.0.0" # node abi 45
         - CB_VERSION="enterprise-4.0.0-rc0"
     - os: osx
       env:
         - NODE_VERSION="3.3.0" # node abi 45
         - CB_VERSION="enterprise-4.0.0-rc0"
     - os: osx
       env:
         - NODE_VERSION="0.12.7" # node abi 14
         - CB_VERSION="enterprise-3.0.3"
     - os: osx
       env:
         - NODE_VERSION="0.12.7" # node abi 14
         - CB_VERSION="enterprise-4.0.0-rc0"
     - os: osx
       env:
         - NODE_VERSION="0.10.40" # node abi 11
         - CB_VERSION="enterprise-4.0.0-rc0"

before_install:
  - rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g json
  - if [ $(uname -s) == 'Linux' ]; then docker pull corbinu/couchbase-test:$CB_VERSION; fi;
  - if [ $(uname -s) == 'Linux' ]; then export CB_ID=$(docker run -d -p 8091:8091 --env BUCKET=default corbinu/couchbase-test:$CB_VERSION); fi;
  - if [ $(uname -s) == 'Linux' ]; then CBRES=0; while [ $CBRES != 1 ]; do echo -n '.'; R=$(docker inspect $CB_ID | json -a State.Running); if [ "$R" == "true" ]; then let CBRES=1; else sleep 1.3; fi; done; fi;
  - if [ $(uname -s) == 'Linux' ]; then export CB_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' $CB_ID); fi;
  - if [ $(uname -s) == 'Linux' ]; then export CNCSTR="http://$CB_IP:8091/"; fi;
  - if [ $(uname -s) == 'Linux' ]; then docker exec -it $CB_ID couchbase-bootstrap bootstrap; fi;

install:
  - npm install
  - if [ $(uname -s) == 'Linux' ]; then make test; fi;

script:
  - echo "done"
