sudo: required

language: node_js

services:
  - docker

os:
  - linux
  - osx

matrix:
  include:
     # Linux
     - os: linux
       env:
         - NODE_VERSION="3.3.0" # node abi 45
         - CB_VERSION="enterprise-4.0.0-rc0"
     - os: linux
       env:
         - NODE_VERSION="2.4.0" # node abi 44
         - CB_VERSION="enterprise-4.0.0-rc0"
     - os: linux
       env:
         - NODE_VERSION="1.8.4" # node abi 43
         - CB_VERSION="enterprise-4.0.0-rc0"
     - os: linux
       env:
         - NODE_VERSION="0.12.7" # node abi 14
         - CB_VERSION="enterprise-3.0.3"
     - os: linux
       env:
         - NODE_VERSION="0.12.7" # node abi 14
         - CB_VERSION="enterprise-4.0.0-rc0"
     - os: linux
       env:
         - NODE_VERSION="0.10.40" # node abi 11
         - CB_VERSION="enterprise-4.0.0-rc0"
     # OS X
     - os: osx
       env:
         - NODE_VERSION="3.3.0" # node abi 45
         - CB_VERSION="enterprise-4.0.0-rc0"
     - os: osx
       env:
         - NODE_VERSION="2.4.0" # node abi 44
         - CB_VERSION="enterprise-4.0.0-rc0"
     - os: osx
       env:
         - NODE_VERSION="1.8.4" # node abi 43
         - CB_VERSION="enterprise-4.0.0-rc0"
     - os: osx
       env:
         - NODE_VERSION="0.12.7" # node abi 14
         - CB_VERSION="enterprise-3.0.3"
     - os: osx
       env:
         - NODE_VERSION="0.12.7" # node abi 14
         - CB_VERSION="enterprise-4.0.0-rc0"
     - os: osx
       env:
         - NODE_VERSION="0.10.40" # node abi 11
         - CB_VERSION="enterprise-4.0.0-rc0"

before_install:
  - rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - docker pull couchbase/server:$CB_VERSION
  - export CP_ID=$(docker run -d -p 8091:8091 couchbase/server:$CB_VERSION)
  - docker ps -a
  - echo $CP_ID
  - export CNCSTR="http://$(export docker inspect --format '{{ .NetworkSettings.IPAddress }}':8091/"
  - echo $CNCSTR

install:
  - npm install
test:
  - make test
coverage:
  - make cover
