sudo: required

language: cpp

services:
- docker

env:
  global:
  - secure: "UKNm/gvplelh+S4A4NDZVyMwCUrVDJiojCMYQW7DcAYnMRbX5aFnrYery5MlmiCzR4EOxGR3v9hoqvTedoEwuRy3MMCYYamSaTm7Tf0KFBz/ubCvAjpeMVXvOSvHEC06mJOEEewGcUTZDq6DuoAt9erRsUc9myqarx+VGoNB5czOlp6g26d07wCRCvdQV4wtCFMMPqdmJi4P2Xq8LxohSZ9sAnUXJ3y7yZ4fTW5djn+8SAdwe+IQPuJy/ph3lBlZ2Om95Cys/kW9CoM2pQFxWG+11h0prpKn2JaEX0R+QeU2ZPhf+CBzBcQi7Px+XXg55NZmkuImyoHvKh3YOP9qN/C3k/tkp59Y2H4CgB5qyre454hb9BxCHqpdsr/ks1CeFhcoxnrzzepcKcyL1pVnhXYOS1UeIm9IVo1/Q+WuRvkOB8kI97LkhpBUgXBLOWVUG90vLQeSJSVYlwkp30xVQYcJiXbjZ8MVeVqRZyO9RMPjcKpuekLtgDsIKIMzqUmYItaMtxwqW1t74nWPGqKE9Lze1LU3VPAb2D0gKHoyKIQg6wRN/gQ6c6KkNs5onlRtPfCpg+ZTN7RKScOYnRAhZsrfwP7/UYNbYgKDJF0hYc1qlT0z7cKZgKiTcbWJ0MnAuGXPwKZUi1W+NcygGjwcA/84dTpp7ZJKYqfthn61v64="

matrix:
  include:
  - os: linux
    env:
    - NODE_VERSION="4.1.0"
    - CB_VERSION="enterprise-3.0.3"
  - os: linux
    env:
    - NODE_VERSION="3.3.1"
    - CB_VERSION="enterprise-3.0.3"
  - os: linux
    env:
    - NODE_VERSION="0.12.7"
    - CB_VERSION="enterprise-3.0.3"
  - os: linux
    env:
    - NODE_VERSION="0.10.40"
    - CB_VERSION="enterprise-3.0.3"
  - os: osx
    env:
    - NODE_VERSION="4.1.0"
    - CB_VERSION="enterprise-3.0.3"
  - os: osx
    env:
    - NODE_VERSION="3.3.1"
    - CB_VERSION="enterprise-3.0.3"
  - os: osx
    env:
    - NODE_VERSION="0.12.7"
    - CB_VERSION="enterprise-3.0.3"
  - os: osx
    env:
    - NODE_VERSION="0.10.40"
    - CB_VERSION="enterprise-3.0.3"
before_install:
- rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
- source ~/.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- npm install -g json
- if [ $(uname -s) == 'skip' ]; then docker pull corbinu/couchbase-test:$CB_VERSION;
  fi;
- if [ $(uname -s) == 'skip' ]; then export CB_ID=$(docker run -d -p 8091:8091 --env
  BUCKET=default corbinu/couchbase-test:$CB_VERSION); fi;
- if [ $(uname -s) == 'skip' ]; then CBRES=0; while [ $CBRES != 1 ]; do echo -n '.';
  R=$(docker inspect $CB_ID | json -a State.Running); if [ "$R" == "true" ]; then
  let CBRES=1; else sleep 1.3; fi; done; fi;
- if [ $(uname -s) == 'skip' ]; then export CB_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress
  }}' $CB_ID); fi;
- if [ $(uname -s) == 'skip' ]; then export CNCSTR="http://$CB_IP:8091/"; fi;
- if [ $(uname -s) == 'skip' ]; then docker exec -it $CB_ID couchbase-bootstrap bootstrap;
  fi;

install:
- export PATH=./node_modules/.bin/:$PATH
- npm install
- if [ $(uname -s) == 'skip' ]; then make test; fi;
- if [[ $TRAVIS_TAG && ${TRAVIS_TAG-x} ]]; then prebuild --target $NODE_VERSION --upload $GITHUB_TOKEN; fi;

script:
- echo done

deploy:
  provider: npm
  email: corbinu@openswimsoftware.com
  api_key:
    secure: fYC1h6YaEcHeHPPJgxMA9DfFp+OBpq9x1NXpXiueqHtihDGXO23WK5MCTqKmuh52lIr+G0Sr9QcF0fXbKzH4qzN38+awbQNaj/uVi3uVDZheeqRRUJquu9prMEv9m6rNyxt4T1KjjRyPL9URgkkUHu3T/zKAsHPgYCr34OIqRGRlKsIKGRRoFYCrHYOd5z216ALQfdnxgWLjE8aZo50mwbPR+hl2FR7AlBpdOS5FmbTijS2JpQZweVq62G6cGj3X2womwKUiO8CarU1rZiAoGfF6dZPMnoTIN2EUI5T1pOM389sKnUsR+K/x80hIo8SO1aOehMavzbvPi5F8pSeWyW3ga/P81y0CGSZnU5ZZNXAAdv6EGT8PfFK8nWxRjSXX4ti8mx3U9rA5cHYkcBs23yjgG5/r1DLJFgiwpoLGGK8TqKNcnPyyqUQsIuo3cSqen9rK7Doyd0J4U/bbqEZRqGZOIZ2pzSw85+KKtZDecuQ0ZPvAWTR4Z+IoAG/J3/8Nht9VWAKa/7x8cb/uaUIASGHDnGneLcx7MCunJ6Z8q8RGOYFIZ78KtGMEi4Nj9UJTep5Ou+i56e+myHUf2RvoYoky5W9tEDVz/70NM+Hr2E91vgEAM3q7XwohCb0rWjShu6IhcBfZJ1dnkKBdlWAkcvKDiGS6QWBhBgN73TlPVhk=
  on:
    tags: true
    repo: corbinu/couchnode
    condition: $NODE_VERSION = '4.0.0'
