sudo: required

language: cpp

services:
- docker

env:
  global:
  - secure: X76FUL3vL1+1x1ojXr5Fu6OZUZXrgiFiOGRtlfUmptrV4h4cTT4xcPQU3Em/Fw+eWytj+0SIKcOsMm8DfPoBPPgY97euMxOA6m3bvbGhusjEZikOYyJa+aLXwFCmqalRt4xFXZqMNnCpxvKHvkiHTrLD72GjfhRhsR2rHNE9M8X7S3PUwgN5dFCwrceRawMXiDeY+jXf17w3g/GX5gz64orQyqg/iHSVFalxGP/QNzOzFaV3UGdIVZXaXBMGc25ha8qOsm1aTZSEYEnDm+cjpIy7+i3kFWphObZxkOKTTuXixvtueJ5wQqS9ikWpMNry0fKlQsfHMhYVHDJBxTayaryoZUSWCGsu6LbzV+VzuL1GxQ24PJoQvIYC47344yy9eZ1qfSKcNiU7v5ecjSLd2nDUDwe3SYrQQhGGzxBW/5fOKS++bkV+I8Py7ceLmmmdSxJeNdYSBRxeokCxncRwmIsj4RRlJWjMKeIzLMLsay7SbxOWJ0WO98M6rQoYOHpJnhDqt7trG3e6K/auu6tc1X8zGjlIUpHSG9fe5HOCj7rxmsp1bgLgFgvzGcMQp91/d4uMVysvQDjHz0Aix1iPCQSCpWLIUubzeJdIPLgnH08NFN8KymDmmvtYMMOrzRI/8mgRkViYMQ6c+caB4HUMMVvQA50Z8dgBlZK/Hk+OJdk=
  - secure: L9HSzsUDffoySqU5yjJUwsIb+yXjsly3FimkiGeM0QhZq6znrGep2JDqgnEZEZGhr0Lr1wuPaCH2Y080e7h+AsF09Vp8nrQKSu1i0F0BGUI9ltw54XbL9W6H8CjgJSKgPJzR4PzKgsYzTWHhESu9RAV3/dfvrw83qIXLRB5JPsLr6SFmBiYLvWqZ9yHvxWtKtGL8eOMMO/3+JwD3xFg0IxjVoV3OaGQEkM5mLgHXIdeDIwp02LnygF6I8GdOUlEeI0BNUZucRlpnJQZSz4/BaJCff9ByQAKqvfG+afsg9pV791wmX4E0WIdSD+gA0ssOpeVG70TnL8bqVboe0AIACwFKl+LvaIE7PHP0pCy9F3HX/hLY7SMbm8RjN0KHCvaBM7Hlw2sPkXQ0JWZEyAK/2RYPHZ6u6eM0buhuH/73/OLeT4HPa3wfom8ZdSFnbSEtuFjqRZ1uDaAILIkl88quq6+xTlL/ArxaaE0Q6tkAm29VGkQ8v1yMkKtPg33WTJ9M+ixFor0YkIDT34BdLirKTw/hfkwhAXNXUOyQqJyDHchQ4TCrdU8D3CRDLeR3ogk1XqjRahjEaEewiytScU9X/bUZuzVYw1NLI/auVrpo5/qk+d+xIpzzg6TF397fxMSYT4QozF2mNb/CdjiEQ9K3kU/olGYaGK4+FdstkVu3OZU=

matrix:
  include:
  - os: linux
    env:
    - NODE_VERSION="4.0.0"
    - CB_VERSION="enterprise-3.0.3"
  - os: linux
    env:
    - NODE_VERSION="3.3.0"
    - CB_VERSION="enterprise-3.0.3"
  - os: linux
    env:
    - NODE_VERSION="0.12.7"
    - CB_VERSION="enterprise-3.0.3"
  - os: linux
    env:
    - NODE_VERSION="0.10.40"
    - CB_VERSION="enterprise-3.0.3"
  - os: osx
    env:
    - NODE_VERSION="4.0.0"
    - CB_VERSION="enterprise-3.0.3"
  - os: osx
    env:
    - NODE_VERSION="3.3.0"
    - CB_VERSION="enterprise-3.0.3"
  - os: osx
    env:
    - NODE_VERSION="0.12.7"
    - CB_VERSION="enterprise-3.0.3"
  - os: osx
    env:
    - NODE_VERSION="0.10.40"
    - CB_VERSION="enterprise-3.0.3"
before_install:
- rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
- source ~/.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- npm install -g json
- if [ $(uname -s) == 'skip' ]; then docker pull corbinu/couchbase-test:$CB_VERSION;
  fi;
- if [ $(uname -s) == 'skip' ]; then export CB_ID=$(docker run -d -p 8091:8091 --env
  BUCKET=default corbinu/couchbase-test:$CB_VERSION); fi;
- if [ $(uname -s) == 'skip' ]; then CBRES=0; while [ $CBRES != 1 ]; do echo -n '.';
  R=$(docker inspect $CB_ID | json -a State.Running); if [ "$R" == "true" ]; then
  let CBRES=1; else sleep 1.3; fi; done; fi;
- if [ $(uname -s) == 'skip' ]; then export CB_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress
  }}' $CB_ID); fi;
- if [ $(uname -s) == 'skip' ]; then export CNCSTR="http://$CB_IP:8091/"; fi;
- if [ $(uname -s) == 'skip' ]; then docker exec -it $CB_ID couchbase-bootstrap bootstrap;
  fi;

install:
- export PATH=./node_modules/.bin/:$PATH
- npm install
- node-pre-gyp package testpackage
- if [ $(uname -s) == 'skip' ]; then make test; fi;
- if [[ $TRAVIS_TAG && ${TRAVIS_TAG-x} ]]; then node-pre-gyp publish; fi;
- if [[ $TRAVIS_TAG && ${TRAVIS_TAG-x} ]]; then npm publish; fi;

script:
- echo done

deploy:
  provider: npm
  email: corbinu@decimal.io
  api_key:
    secure: fYC1h6YaEcHeHPPJgxMA9DfFp+OBpq9x1NXpXiueqHtihDGXO23WK5MCTqKmuh52lIr+G0Sr9QcF0fXbKzH4qzN38+awbQNaj/uVi3uVDZheeqRRUJquu9prMEv9m6rNyxt4T1KjjRyPL9URgkkUHu3T/zKAsHPgYCr34OIqRGRlKsIKGRRoFYCrHYOd5z216ALQfdnxgWLjE8aZo50mwbPR+hl2FR7AlBpdOS5FmbTijS2JpQZweVq62G6cGj3X2womwKUiO8CarU1rZiAoGfF6dZPMnoTIN2EUI5T1pOM389sKnUsR+K/x80hIo8SO1aOehMavzbvPi5F8pSeWyW3ga/P81y0CGSZnU5ZZNXAAdv6EGT8PfFK8nWxRjSXX4ti8mx3U9rA5cHYkcBs23yjgG5/r1DLJFgiwpoLGGK8TqKNcnPyyqUQsIuo3cSqen9rK7Doyd0J4U/bbqEZRqGZOIZ2pzSw85+KKtZDecuQ0ZPvAWTR4Z+IoAG/J3/8Nht9VWAKa/7x8cb/uaUIASGHDnGneLcx7MCunJ6Z8q8RGOYFIZ78KtGMEi4Nj9UJTep5Ou+i56e+myHUf2RvoYoky5W9tEDVz/70NM+Hr2E91vgEAM3q7XwohCb0rWjShu6IhcBfZJ1dnkKBdlWAkcvKDiGS6QWBhBgN73TlPVhk=
  on:
    tags: true
    repo: corbinu/couchnode
    condition: $NODE_VERSION = '4.0.0' && $(uname -s) == 'Linux'
