sudo: required
dist: trusty
language: cpp
services:
- docker
matrix:
  include:
  - os: linux
    env:
    - OS="Linux"
    - NODE_VERSION="5.6.0"
    - CB_VERSION="enterprise-3.0.3"
  - os: osx
    env:
    - NODE_VERSION="5.6.0"
    - CB_VERSION="enterprise-3.0.3"
before_install:
- rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
- source ~/.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- npm install -g json
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull corbinu/couchbase-test:$CB_VERSION;
  docker pull corbinu/alpine-node-builder; fi;
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CB_ID=$(docker run -d -p 8091:8091
  --env BUCKET=default corbinu/couchbase-test:$CB_VERSION); fi;
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CBRES=0; while [ $CBRES != 1 ]; do echo
  -n '.'; R=$(docker inspect $CB_ID | json -a State.Running); if [ "$R" == "true"
  ]; then let CBRES=1; else sleep 1.3; fi; done; fi;
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CB_IP=$(docker inspect --format
  '{{ .NetworkSettings.IPAddress}}' $CB_ID); fi;
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CNCSTR="http://$CB_IP:8091/";
  fi;
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker exec -it $CB_ID couchbase-bootstrap
  bootstrap; fi;
install:
- export PATH=./node_modules/.bin/:$PATH
- npm install
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make test; fi;
- mkdir -p prebuilds/@corbinu
- if [[ "$TRAVIS_BRANCH" = "master" ]]; then prebuild --upload $GITHUB_TOKEN -b 6.0.0
  -b 5.6.0 -b 4.3.0; fi;
- if [[ "$TRAVIS_BRANCH" = "master" ]]; then if [[ "$TRAVIS_OS_NAME" == "linux" ]];
  then docker run -t --volume "$(pwd):/install" corbinu/alpine-node-builder prebuild
  --libc=musl --upload $GITHUB_TOKEN -b 6.0.0 -b 5.6.0 -b 4.3.0; fi; fi;
script:
- echo done
deploy:
  provider: npm
  api_key:
    secure: DYA5VWbrYp9GG4zp/inkLtCvq6Vpj6VUXbXFopKwndIZM5BmA4aJRVXw4IM4gHx/gJ1b7T73JrDpbC7V6Z4Uou8e89YgHWsdZRui3Y3kfuoJ7QLiX8mGKzRlAZEIDPdd0NyWn1eCuHQKE6qavSXgS3b/TZ+LY9XDJ0I4gvbZlFYNo5HzLsAsjjQXxDXGX7zR27Q9XJ0S2yYodLOK++AEhVKHGspfbhNOY/p6OHDvMkYfr88kC12ZRt2eduY2etQ4MBlAt1lepwexPanD26Y3YcVO15ODCvDzzmTJquH90iHMXu2OkagFAXDLFKDPANHOqr0agmF6hkmDrJqeRVNsyfh5MdNvjdUAlBcCeeas1Ya31YR9HEjwhVdSjOAiiThPj4ReRQYAzapR0L8iVhR94x5ewUi96GlW3PpzSZaBbaVC+rjVrgzeZsuzmMXlrjr34b5QCr4VFjKGl39O/jaY+wozUuzgcQiHOUucMYSJArF3mUEGOFzWdtlWX+CGJMRUmOdN/j0wj+U442mAKY0ZsAomdvtTC6LvIjjJn/XCihwkoDHlrdhiuPnLnL1+bJOtYAltxIe97+qjgMokNMG8Vg5AbSKbRVm+CsVe5iTXwx9QVI9eA60Lf6v68mkiOiZ9TZRfQojcCEzpVBd1m1pzBsIO1XCpFxyxiQpBb43rXQs=
  on:
    repo: corbinu/couchnode
    condition: $TRAVIS_OS_NAME == "linux"
    tags: true
