sudo: required
dist: trusty
language: java
services:
- docker
matrix:
  include:
  - os: linux
    env:
    - OS="Linux"
    - NODE_VERSION="10.0.0"
    - CB_VERSION="enterprise-5.1.0"
  - os: osx
    env:
    - NODE_VERSION="10.0.0"
    - CB_VERSION="enterprise-5.1.0"
before_install:
- rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
- source ~/.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
install:
- export PATH=./node_modules/.bin/:$PATH
- npm install
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make test; fi;
- mkdir -p prebuilds/@corbinu
- if [[ "$TRAVIS_BRANCH" = "master" ]]; then prebuild --upload $GITHUB_TOKEN -t 8.0.0 -t 6.9.1 -t 9.0.0; fi;
- if [[ "$TRAVIS_BRANCH" = "master" ]]; then if [[ "$TRAVIS_OS_NAME" == "linux" ]];
  then docker run -t --volume "$(pwd):/install" corbinu/alpine-node-builder prebuild
  --libc=musl --upload $GITHUB_TOKEN -t 8.0.0 -t 9.0.0 -t 10.0.0; fi; fi;
script:
- echo done
deploy:
  provider: npm
  email: corbinu@openswimsoftware.com
  api_key:
    secure: YH8ZTPYYQVxOWwNOGauPgmE5/SctgcaJsqggOIg5HRb7TZqYIL3zxSi8uYRxbh9mUCwqnx7QtWr3pQv1WAS0f5Sii0SKYHOmn3af6VBeV/Pga8u1jiA/TkH/l6LqDRjnP/MPFQ82c4ZhTAp/fFQet8/c7YMb21JfNXHbOUJ44fB4cOWreuDurlJVhI5Qh/3RIW+ZjTFKgF9RrJA8NaDfKl60lshlhCxZjn+CuatQbhCsrA5gfeBKrtlM+Z4DLEJ4ScOO0bU2YXLMwx+hB7Sj8TLDntuQ1pGb9MezELrvREQVuqAxWgi1EaNs1B+2Op++fElW2yKWgUPButgvgilWUJpltJuAe273tFXeGyl3owJvfvZ9AmUe76n8tZ8WLZGBnvw7XnVw6OLUW6l9vSRsNmVLXCR1NG7r2mpbkvuIBDQ68tN0CMj+acXE/7IXdNbqjSQTBUzMY/YxXMdrwZJ8rM8+qr3F3/wa8wZNtxuPjRSAPUy4rmJMpQboinjGfhJ/xfvfji2yQe8v8rycn+I0iHSnLazMIoC3rzTNvYzZGRPe/1V0YFTwo0suF5WtfK1pfdKWlJnPViNo41wBcCAHcZ5f/GyFWEWOoAia3GGOZzZ9Zvxmy5yFRKT0oFfHfyPn76RTk4AiDpyFdQbAGe4g8GQaEFwJUpahgOTALh0YmXk=
  on:
    tags: true
    condition: $TRAVIS_OS_NAME == "linux"
    repo: corbinu/couchnode
