language: node_js

os:
  - linux
  - osx

matrix:
  include:
     # Linux
     - os: linux
       env: NODE_VERSION="3.3.0" # node abi 45
     - os: linux
       env: NODE_VERSION="2.4.0" # node abi 44
     - os: linux
       env: NODE_VERSION="1.8.4" # node abi 43
     - os: linux
       env: NODE_VERSION="0.12.7" # node abi 14
     - os: linux
       env: NODE_VERSION="0.10.40" # node abi 11
     # OS X
     - os: osx
       env: NODE_VERSION="3.3.0" # node abi 45
     - os: osx
       env: NODE_VERSION="2.4.0" # node abi 44
     - os: osx
       env: NODE_VERSION="1.8.4" # node abi 43
     - os: osx
       env: NODE_VERSION="0.12.7" # node abi 14
     - os: osx
       env: NODE_VERSION="0.10.40" # node abi 11

install:
  - npm install
test:
  - npm test
